version: "3.7"

services:
  coqui-tts:
    image: ghcr.io/coqui-ai/tts-cpu
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.coqui-tts.rule=Host(`coqui.nudge8.com`)
      - traefik.http.routers.coqui-tts.entrypoints=websecure
      - traefik.http.routers.coqui-tts.tls=true
      - traefik.http.services.coqui-tts.loadbalancer.server.port=5002

networks:
  traefik-public:
    external: true
