version: "3.8"

services:
  coqui-tts:
    build: .
    container_name: coqui-tts
    restart: unless-stopped
    networks:
      - traefik_network  # Replace with your Traefik network name
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coqui-tts.rule=Host(`coqui.nudge8.com`)"
      - "traefik.http.routers.coqui-tts.entrypoints=websecure"
      - "traefik.http.routers.coqui-tts.tls=true"
      - "traefik.http.services.coqui-tts.loadbalancer.server.port=8000"

networks:
  traefik_network:
    external: true  # Ensure this network exists in Docker
