version: "3.8"

services:
  coqui-tts:
    build: .           # Keep this for local builds
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coqui-tts.rule=Host(`coqui.nudge8.com`)"
      - "traefik.http.routers.coqui-tts.entrypoints=websecure"
      - "traefik.http.routers.coqui-tts.tls=true"
      - "traefik.http.services.coqui-tts.loadbalancer.server.port=8000"

networks:
  traefik_network:
    external: true     # Ensure this network exists
