version: "3.8"

services:
  coqui-tts:
    image: coqui-tts-app:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.coqui-tts.rule=Host(`coqui.nudge8.com`)
        - traefik.http.routers.coqui-tts.entrypoints=https
        - traefik.http.routers.coqui-tts.tls=true
        - traefik.http.routers.coqui-tts.tls.certresolver=le
        - traefik.http.services.coqui-tts.loadbalancer.server.port=5002
    ports:
      - "5002:5002"
    networks:
      - traefik-public
    volumes:
      - tts-data:/app/data

volumes:
  tts-data:

networks:
  traefik-public:
    external: true
